/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Dominik Messerschmidt
 */
public class MainFrame extends javax.swing.JFrame
{

    Node current;

    public String getCurrentText()
    {
        if (current != null)
        {
            return current.text;
        }
        else
        {
            return "";
        }
    }

    public boolean pickNode(int i)
    {
        if (current != null && current.children != null && i < current.children.length)
        {
            current = current.children[i].children[0];
            onCurrentNodeChanged();
            return true;
        }
        else
        {
            return false;
        }
    }

    public void handleNode(Node root)
    {
        current = root;
        onCurrentNodeChanged();
    }

    public void onCurrentNodeChanged()
    {
        if (current.isEnd())
        {
            titleText.setText("You are: " + current.text);
            buttonOption1.setText("Restart");
            buttonOption2.setText("");
            buttonOption3.setText("");
            buttonOption2.setVisible(false);
            buttonOption3.setVisible(false);
        }
        else
        {
            titleText.setText(current.text);
            if (current.children.length > 0 && current.children[0] != null)
            {
                buttonOption1.setText(current.children[0].text);
                buttonOption1.setVisible(true);
            }
            else
            {
                buttonOption1.setVisible(false);
            }
            if (current.children.length > 1 && current.children[1] != null)
            {
                buttonOption2.setText(current.children[1].text);
                buttonOption2.setVisible(true);
            }
            else
            {
                buttonOption2.setVisible(false);
            }
            if (current.children.length > 2 && current.children[2] != null)
            {
                buttonOption3.setText(current.children[2].text);
                buttonOption3.setVisible(true);
            }
            else
            {
                buttonOption3.setVisible(false);
            }
        }
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        titleText = new javax.swing.JTextArea();
        buttonOption1 = new javax.swing.JButton();
        buttonOption2 = new javax.swing.JButton();
        buttonOption3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);

        titleText.setEditable(false);
        titleText.setColumns(20);
        titleText.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        titleText.setLineWrap(true);
        titleText.setRows(5);
        titleText.setText("Do you want to cast magic or smash things?");
        titleText.setWrapStyleWord(true);
        titleText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(titleText);

        buttonOption1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonOption1.setText("Would you like to hear about my God?");
        buttonOption1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOption1ActionPerformed(evt);
            }
        });

        buttonOption2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonOption2.setText("I actually prefer animals to people");
        buttonOption2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOption2ActionPerformed(evt);
            }
        });

        buttonOption3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonOption3.setText("My fists hunger for Justice!");
        buttonOption3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOption3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOption1)
                            .addComponent(buttonOption2)
                            .addComponent(buttonOption3))
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOption1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOption2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOption3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOption1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOption1ActionPerformed
    {//GEN-HEADEREND:event_buttonOption1ActionPerformed
        if (current.isEnd())
        {
            Main.restart();
        }
        else
        {
            pickNode(0);
        }
    }//GEN-LAST:event_buttonOption1ActionPerformed

    private void buttonOption2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOption2ActionPerformed
    {//GEN-HEADEREND:event_buttonOption2ActionPerformed
        pickNode(1);
    }//GEN-LAST:event_buttonOption2ActionPerformed

    private void buttonOption3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOption3ActionPerformed
    {//GEN-HEADEREND:event_buttonOption3ActionPerformed
        pickNode(2);
    }//GEN-LAST:event_buttonOption3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOption1;
    private javax.swing.JButton buttonOption2;
    private javax.swing.JButton buttonOption3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea titleText;
    // End of variables declaration//GEN-END:variables
}
