/*
 * Copyright (C) 2023 Dominik Messerschmidt
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui;

import javax.swing.JOptionPane;
import main.Actor;
import main.Equip;
import main.EquipItem;
import main.Game;
import main.Item;
import main.Weapon;
import main.WeaponItem;

/**
 *
 * @author Dominik Messerschmidt
 */
public class ShopFrame extends javax.swing.JDialog
{

    public static final Item[] ITEMS = new Item[]
    {
        Item.POTION,
        Item.THROWING_KNIFE,
        Item.CROSSBOW,
        Item.DIFFUSE_KIT,
        new WeaponItem(Weapon.DAGGER),
        new WeaponItem(Weapon.SWORD),
        new WeaponItem(Weapon.SPEAR),
        new WeaponItem(Weapon.BATTLEAXE),
        new WeaponItem(Weapon.LONGSWORD),
        new WeaponItem(Weapon.HALBERD),
        new WeaponItem(Weapon.ZWEIHANDER),
        new WeaponItem(Weapon.DRAGONSWORD),
        new EquipItem(Equip.HELMET),
        new EquipItem(Equip.SHIELD),
        new EquipItem(Equip.ARMOR),
    };

    /**
     * Creates new form ShopFrame
     */
    public ShopFrame()
    {
        super(MainFrame.getInstance());

        initComponents();
        setTitle("SHOP");
        setLocation(MainFrame.getInstance().getX() + MainFrame.getInstance().getWidth() / 2, MainFrame.getInstance().getY() + MainFrame.getInstance().getHeight() / 2);
        setModal(true);
        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {

            public int getSize()
            {
                return ITEMS.length;
            }

            public String getElementAt(int i)
            {
                return ITEMS[i].toString();
            }
        });
        update();
    }

    public void update()
    {
        int index = jList1.getSelectedIndex();
        if (index >= 0)
        {
            Item i = ITEMS[index];
            name.setText(i.toString());
            description.setText(i.getDescription());
            cost.setText("Price: " + i.getValue() + " Gold");
        }
        else
        {
            name.setText("No item selected");
            description.setText("");
            cost.setText("");
        }
        Actor a = Game.getInstance().getActorOnTurn();
        character.setText("Character: " + a);
        gold.setText("Gold: " + a.getGold());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        name = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        character = new javax.swing.JLabel();
        gold = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jList1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        name.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        name.setText("No item selected");

        title.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        title.setText("SHOP");

        cost.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        character.setText("Character: ");

        gold.setText("Gold: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(character)
                        .addGap(18, 18, 18)
                        .addComponent(gold)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(character)
                        .addComponent(gold)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jList1ValueChanged
    {//GEN-HEADEREND:event_jList1ValueChanged
        update();
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        int index = jList1.getSelectedIndex();
        if (index >= 0)
        {
            Actor a = Game.getInstance().getActorOnTurn();
            Item i = ITEMS[index];
            if (a.getGold() < i.getValue())
            {
                System.out.println("Not enough gold");
                JOptionPane.showMessageDialog(this, "Not enough gold");
            }
            else
            {
                a.addItem(i);
                a.setGold(a.getGold() - i.getValue());
                JOptionPane.showMessageDialog(this, a + " got " + i);
            }
            update();
        }
        else
        {
            System.out.println("No item selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel character;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel description;
    private javax.swing.JLabel gold;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
