/*
 * Copyright (C) 2017 Dominik Messerschmidt <dominik.messerschmidt@continental-corporation.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package graphic;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.LinkedList;
import javax.swing.JLabel;

/**
 *
 * @author Dominik Messerschmidt
 * <dominik.messerschmidt@continental-corporation.com>
 */
public class ImageGridPanel extends javax.swing.JPanel
{

    private int columns = 5;
    private final int maxWidth = 256, maxHeight = 256;
    private final MouseAdapter mouseCallback = new MouseAdapter()
    {
        @Override
        public void mouseClicked(MouseEvent e)
        {
            try
            {
                JLabel sourceLabel = (JLabel) e.getSource();
                File root = new File(sourceLabel.getToolTipText());
                String command = "explorer " + root.getParent();
                System.out.println("Executing " + command);
                Runtime.getRuntime().exec(command);
            } catch (Exception ex)
            {
                System.err.println(ex.toString());
            }
        }

    };

    /**
     * Creates new form ImageGridPanel
     */
    public ImageGridPanel()
    {
        initComponents();
    }

    public void setImages(LinkedList<BufferedImage> images, LinkedList<File> associatedFiles)
    {
        System.out.println("ImageGridPanel.setImages()");
        this.removeAll();
        setLayout(new GridLayout(images.size() / columns + 1, columns));
        int i = 0;
        for (BufferedImage image : images)
        {
            JLabel label;
            if (image.getWidth() > maxWidth || image.getHeight() > maxHeight)
            {
                label = new JLabel(new javax.swing.ImageIcon(image.getScaledInstance(maxWidth, maxHeight, 0)));
            }
            else
            {
                label = new JLabel(new javax.swing.ImageIcon(image));
            }
            add(label);
            if (i < associatedFiles.size())
            {
                label.setToolTipText(associatedFiles.get(i).getAbsolutePath());
                label.addMouseListener(mouseCallback);
            }
            i++;
            ProgressPanel.getInstance().setProgress(100 * i / images.size());
            if (main.Main.interruptFlag)
            {
                break;
            }
        }
    }

    public void setColumns(int cols)
    {
        columns = cols;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
