/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dominik
 */
public class MainFrame extends javax.swing.JFrame {
    private int antwort;
    private String buffer;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setSchriftgroesse(24);
        this.setSize(800, 1000);
    }

    public int getAnwort()
    {
        antwort = akinator.Akinator.KA;
        jaButton.requestFocusInWindow();
        while(antwort==akinator.Akinator.KA)try {
            Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        return antwort;
    }
    
    public String getInput()
    {
        buffer = null;
        input.requestFocusInWindow();
        while(buffer == null)try {
            Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        return buffer;
    }
    
    public void println(String text)
    {
        output.append(text+"\n");
    }
    
    public void clearOutput()
    {
        output.setText("");
    }
    
    public void setSchriftgroesse(int size){
        jaButton.setFont(new java.awt.Font("Calibri", 0, size));
        neinButton.setFont(new java.awt.Font("Calibri", 0, size));
        input.setFont(new java.awt.Font("Calibri", 0, size));
        output.setFont(new java.awt.Font("Calibri", 0, size));
        vielleichtButton.setFont(new java.awt.Font("Calibri", 0, size));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jaButton = new javax.swing.JButton();
        neinButton = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        vielleichtButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        schriftMenu = new javax.swing.JMenu();
        s12 = new javax.swing.JMenuItem();
        s14 = new javax.swing.JMenuItem();
        s16 = new javax.swing.JMenuItem();
        s18 = new javax.swing.JMenuItem();
        s20 = new javax.swing.JMenuItem();
        s24 = new javax.swing.JMenuItem();
        s28 = new javax.swing.JMenuItem();
        s32 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setFocusable(false);
        jScrollPane1.setRequestFocusEnabled(false);

        output.setEditable(false);
        output.setColumns(20);
        output.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        output.setLineWrap(true);
        output.setRows(5);
        output.setFocusable(false);
        jScrollPane1.setViewportView(output);

        jaButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jaButton.setText("Ja");
        jaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaButtonActionPerformed(evt);
            }
        });
        jaButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jaButtonKeyPressed(evt);
            }
        });

        neinButton.setText("Nein");
        neinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neinButtonActionPerformed(evt);
            }
        });
        neinButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                neinButtonKeyPressed(evt);
            }
        });

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        vielleichtButton.setText("Vielleicht");
        vielleichtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vielleichtButtonActionPerformed(evt);
            }
        });
        vielleichtButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vielleichtButtonKeyPressed(evt);
            }
        });

        jMenu1.setText("System");

        jMenuItem1.setText("Baum ausgeben");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Baum bearbeiten");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('O');
        jMenu2.setText("Optionen");

        schriftMenu.setMnemonic('s');
        schriftMenu.setText("Schriftgröße:");

        s12.setText("12");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        schriftMenu.add(s12);

        s14.setText("14");
        s14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s14ActionPerformed(evt);
            }
        });
        schriftMenu.add(s14);

        s16.setText("16");
        s16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s16ActionPerformed(evt);
            }
        });
        schriftMenu.add(s16);

        s18.setText("18");
        s18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s18ActionPerformed(evt);
            }
        });
        schriftMenu.add(s18);

        s20.setText("20");
        s20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20ActionPerformed(evt);
            }
        });
        schriftMenu.add(s20);

        s24.setText("24");
        s24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s24ActionPerformed(evt);
            }
        });
        schriftMenu.add(s24);

        s28.setText("28");
        s28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s28ActionPerformed(evt);
            }
        });
        schriftMenu.add(s28);

        s32.setText("32");
        s32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s32ActionPerformed(evt);
            }
        });
        schriftMenu.add(s32);

        jMenu2.add(schriftMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(neinButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vielleichtButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(input))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vielleichtButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(neinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaButtonActionPerformed
        antwort = akinator.Akinator.JA;
    }//GEN-LAST:event_jaButtonActionPerformed

    private void neinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neinButtonActionPerformed
        antwort = akinator.Akinator.NEIN;
    }//GEN-LAST:event_neinButtonActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        if(input.getText().length() > 0)
        {
            buffer = input.getText();
            input.setText("");
        }
    }//GEN-LAST:event_inputActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        setSchriftgroesse(12);
    }//GEN-LAST:event_s12ActionPerformed

    private void s14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s14ActionPerformed
        setSchriftgroesse(14);
    }//GEN-LAST:event_s14ActionPerformed

    private void s18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s18ActionPerformed
        setSchriftgroesse(18);
    }//GEN-LAST:event_s18ActionPerformed

    private void s20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20ActionPerformed
        setSchriftgroesse(20);
    }//GEN-LAST:event_s20ActionPerformed

    private void s24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s24ActionPerformed
        setSchriftgroesse(24);
    }//GEN-LAST:event_s24ActionPerformed

    private void s28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s28ActionPerformed
        setSchriftgroesse(28);
    }//GEN-LAST:event_s28ActionPerformed

    private void s32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s32ActionPerformed
        setSchriftgroesse(32);
    }//GEN-LAST:event_s32ActionPerformed

    private void jaButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jaButtonKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT)
            neinButton.requestFocusInWindow();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            jaButton.doClick();
    }//GEN-LAST:event_jaButtonKeyPressed

    private void neinButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_neinButtonKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT)
            jaButton.requestFocusInWindow();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            neinButton.doClick();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_RIGHT)
            vielleichtButton.requestFocusInWindow();
    }//GEN-LAST:event_neinButtonKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        akinator.Akinator.printTree();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void vielleichtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vielleichtButtonActionPerformed
        antwort = akinator.Akinator.VIELLEICHT;
    }//GEN-LAST:event_vielleichtButtonActionPerformed

    private void vielleichtButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vielleichtButtonKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_LEFT)
            neinButton.requestFocusInWindow();
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            vielleichtButton.doClick();
    }//GEN-LAST:event_vielleichtButtonKeyPressed

    private void s16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s16ActionPerformed
        setSchriftgroesse(16);
    }//GEN-LAST:event_s16ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        akinator.Frageknoten kopf = akinator.Akinator.lade();
        BaumEditorPanel.showBaumEditorDialog(kopf);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jaButton;
    private javax.swing.JButton neinButton;
    private javax.swing.JTextArea output;
    private javax.swing.JMenuItem s12;
    private javax.swing.JMenuItem s14;
    private javax.swing.JMenuItem s16;
    private javax.swing.JMenuItem s18;
    private javax.swing.JMenuItem s20;
    private javax.swing.JMenuItem s24;
    private javax.swing.JMenuItem s28;
    private javax.swing.JMenuItem s32;
    private javax.swing.JMenu schriftMenu;
    private javax.swing.JButton vielleichtButton;
    // End of variables declaration//GEN-END:variables
}
