/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spiel;

import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Dundun
 */
public class Spielautomat extends javax.swing.JPanel implements ActionListener,KeyListener{
    private Timer t;
    private Timer auto;
    // Anzahl drehender Räder
    private int spinning;
    public final ImageIcon[] ICONS={
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/glumandaIcon.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/bisasamIcon.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/taubsiIcon.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/rattfratzIcon.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/kirsche.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/sonne.png")),
      new javax.swing.ImageIcon(getClass().getResource("/automat/img/7.png"))
    };
    public final int[] WINSUMS={25,25,25,15,10,12,50,100};
    public final int[] INDICES1={0,7,1,2,3,4,5,6};
    public final int[] INDICES2={6,7,3,4,2,1,0,4,3,5,3};
    public final int[] INDICES3={4,7,5,4,3,0,2,3,4,6,3,4,2,1};
    public final int BILDERANZ=3;
        // Indices der Räder
    private final int[] RAD1=new int[BILDERANZ];
    private final int[] RAD2=new int[BILDERANZ];
    private final int[] RAD3=new int[BILDERANZ];
    private Münzkorb geld;
    private int freispiele=0;

    /**
     * Creates new form Spielautomat
     */
    public Spielautomat(int delay) {
        initComponents();
        setLocation(Javamon.getLoc());
        t=new Timer(0,this);
        t.setDelay(delay);
        auto=new Timer(4*delay+delay/2,this);
        spinning=3;
        for(int i=0;i<BILDERANZ;i++){
          RAD1[i]=i;
          RAD2[i]=i;
          RAD3[i]=i;
        }
        geld=Javamon.getSpieler().münzkorb;
        konto.setText("Konto: "+geld.getMünzen());
        paintLabels();
        start.requestFocus();
        setMinimumSize(this.getSize());
        this.addKeyListener(this);
        start.addKeyListener(this);
    }
    
    private void paintLabels(){
      bild1.setIcon(getIconAt(INDICES1[RAD1[2]]));
      bild2.setIcon(getIconAt(INDICES1[RAD1[1]]));
      bild3.setIcon(getIconAt(INDICES1[RAD1[0]]));
      bild4.setIcon(getIconAt(INDICES2[RAD2[2]]));
      bild5.setIcon(getIconAt(INDICES2[RAD2[1]]));
      bild6.setIcon(getIconAt(INDICES2[RAD2[0]]));
      bild7.setIcon(getIconAt(INDICES3[RAD3[2]]));
      bild8.setIcon(getIconAt(INDICES3[RAD3[1]]));
      bild9.setIcon(getIconAt(INDICES3[RAD3[0]]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bild6 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        bild2 = new javax.swing.JLabel();
        bild7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bild1 = new javax.swing.JLabel();
        bild3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bild5 = new javax.swing.JLabel();
        bild4 = new javax.swing.JLabel();
        bild8 = new javax.swing.JLabel();
        bild9 = new javax.swing.JLabel();
        konto = new javax.swing.JLabel();
        lastWin = new javax.swing.JLabel();
        win = new javax.swing.JLabel();
        einsatz = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        freie = new javax.swing.JLabel();

        bild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        start.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        bild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        bild7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        bild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        bild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        bild8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        bild9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automat/img/schiggyIcon.png"))); // NOI18N

        konto.setText("Konto: 0");

        lastWin.setText("letzter Gewinn: 0");

        win.setFont(new java.awt.Font("DokChampa", 1, 18)); // NOI18N
        win.setForeground(new java.awt.Color(0, 204, 0));
        win.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        einsatz.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 5));

        jLabel1.setText("Einsatz");

        freie.setText("Freispiele: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bild2)
                                    .addComponent(bild1)
                                    .addComponent(bild3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(konto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(einsatz))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bild6)
                            .addComponent(bild5)
                            .addComponent(bild4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(win, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bild7)
                    .addComponent(bild8)
                    .addComponent(bild9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(freie))
                    .addComponent(lastWin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bild4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bild5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bild6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bild7)
                            .addComponent(bild1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bild2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bild3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bild8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bild9))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(win, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(freie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastWin)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(einsatz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konto)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        if(t.isRunning()){
            spinning--;
            if(spinning==0){
                t.stop();
                int gewinn=checkWin();
                if(gewinn>0){
                    win.setForeground(new java.awt.Color(0, 204, 0));
                    win.setText("! WINNER !");
                    gewinn=gewinn*(int)einsatz.getValue()/5;
                    geld.addMünzen(gewinn);
                    lastWin.setText("letzter Gewinn: "+gewinn);
                }else{
                    win.setForeground(new java.awt.Color(205,0, 0));
                    win.setText("Loser");
                }
                start.setText("OK");
            }
        }
        else{
            if(spinning!=3){
                spinning=3;
                win.setText("");
                start.setText("START");
            }else{
                if(geld.getMünzen()<(int)einsatz.getValue()){
                    if(auto.isRunning())auto.stop();
                    Javamon.sout("Du hast keine Münzen.");
                    Javamon.displayDefault();
                }else{
                    if(freispiele>0){
                        freispiele--;
                        freie.setText("Freispiele: "+freispiele);
                    }
                    else geld.addMünzen(-(int)einsatz.getValue());
                    t.start();
                    start.setText("STOP");
                }
            }
        }
        einsatz.setEnabled(!t.isRunning()&&freispiele==0);
        konto.setText("Konto: "+geld.getMünzen());
    }//GEN-LAST:event_startActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bild1;
    private javax.swing.JLabel bild2;
    private javax.swing.JLabel bild3;
    private javax.swing.JLabel bild4;
    private javax.swing.JLabel bild5;
    private javax.swing.JLabel bild6;
    private javax.swing.JLabel bild7;
    private javax.swing.JLabel bild8;
    private javax.swing.JLabel bild9;
    private javax.swing.JSpinner einsatz;
    private javax.swing.JLabel freie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel konto;
    private javax.swing.JLabel lastWin;
    private javax.swing.JButton start;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
      if(e.getSource().equals(auto)){
        start.doClick();
        return;
      }
      if(spinning>=1){
        for(int i=0;i<RAD3.length;i++){
          RAD3[i]++;
          if(RAD3[i]>=INDICES3.length)RAD3[i]=0;
        }
      }
      if(spinning>=2){
        for(int i=0;i<RAD2.length;i++){
          RAD2[i]++;
          if(RAD2[i]>=INDICES2.length)RAD2[i]=0;
        }
      }
      if(spinning==3){
        for(int i=0;i<RAD1.length;i++){
          RAD1[i]++;
          if(RAD1[i]>=INDICES1.length)RAD1[i]=0;
        }
      }
      paintLabels();
    }
    
    public ImageIcon getIconAt(int i){
      return ICONS[i];
    }
    
    public int checkWin(){
      int winsum=0;
      //horiontal
      for(int i=0;i<BILDERANZ;i++){
        if(INDICES1[RAD1[i]]==INDICES2[RAD2[i]]&&INDICES1[RAD1[i]]==INDICES3[RAD3[i]]){
            if(INDICES1[RAD1[i]]==6){
                freispiele+=10;
                freie.setText("Freispiele: "+freispiele);
            }
            else winsum+=WINSUMS[INDICES1[RAD1[i]]];
        }
      }
      // diagonal
      if(INDICES1[RAD1[0]]==INDICES2[RAD2[1]]&&INDICES2[RAD2[1]]==INDICES3[RAD3[2]])
          winsum+=WINSUMS[INDICES1[RAD1[0]]];
      if(INDICES1[RAD1[2]]==INDICES2[RAD2[1]]&&INDICES2[RAD2[1]]==INDICES3[RAD3[0]])
          winsum+=WINSUMS[INDICES1[RAD1[2]]];
      // kirschen
      if(winsum==0){
        for(int i=0;i<BILDERANZ;i++){
          if(INDICES1[RAD1[i]]==5) winsum+=WINSUMS[INDICES1[RAD1[i]]]/4;
          if(INDICES2[RAD2[i]]==5) winsum+=WINSUMS[INDICES2[RAD2[i]]]/4;
          if(INDICES3[RAD3[i]]==5) winsum+=WINSUMS[INDICES3[RAD3[i]]]/4;
        }
      }
      return winsum;
    }

    private Container getContentPane() {
        return this;
    }

    @Override
    public void keyTyped(KeyEvent e) {}

    @Override
    public void keyPressed(KeyEvent e) {
        if(e.getKeyCode()==Steuerung.getB())Javamon.displayDefault();
    }

    @Override
    public void keyReleased(KeyEvent e) {}
}
