/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tools;

import spiel.Javamon;

/**
 *
 * @author Dominik
 */
public class PokInfoComponent extends javax.swing.JPanel {
    private pokemon.Pokemon dieses;

    /**
     * Creates new form PokInfoComponent
     */
    public PokInfoComponent() {
        initComponents();
    }
    
    public void setPokemon(pokemon.Pokemon pok)
    {
        dieses = pok;
        paintLabels();
    }
    
    public void paintLabels()
    {
        level.setText("Lvl: "+dieses.getLevel());
        originName.setText(dieses.getOriginName());
        bild.setIcon(dieses.getIcon());
        if(dieses.getFähigkeit()==null)skill.setText("Fähigkeit: Keine");
        else{
          skill.setText("Fähigkeit: "+dieses.getFähigkeit());
          skill.setToolTipText(dieses.getFähigkeit().tooltip);
        }
        typ1.setText(dieses.getTyp1().name()+" /");
        typ2.setText(dieses.getTyp2().name());
        typ1.setForeground(Javamon.TYPEN[dieses.getTyp1().index]);
        typ2.setForeground(Javamon.TYPEN[dieses.getTyp2().index]);
        atk.setText("Angriff:                       "+dieses.getAtk());
        atk.setToolTipText("Angriffskraft: Beeinflusst die Stärke von physichen Attacken");
        vert.setText("Verteidigung:            "+dieses.getVert());
        vert.setToolTipText("Verteidigung: Verringert erlittenen Schaden durch physische Attacken");
        spezatk.setText("Spezialangriff:           "+dieses.getSpezAtk());
        spezatk.setToolTipText("Spezial-Angriffskraft: Beeinflusst die Stärke von nicht-physichen Attacken");
        spezvert.setText("Spezialverteidigung: "+dieses.getSpezVert());
        spezvert.setToolTipText("Spezial-Verteidigung: Verringert erlittenen Schaden durch nicht-physische Attacken");
        init.setText("Initiative:                    "+dieses.getInit());
        init.setToolTipText("Initiative/Beweglichkeit: Beeinflusst Genauigkeit,Volltrefferquote, Ausweichvermögen und Erstschlagchance");
        sum.setText("Wertesumme:         "+dieses.getWerteSumme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typ = new javax.swing.JLabel();
        typ1 = new javax.swing.JLabel();
        typ2 = new javax.swing.JLabel();
        sum = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        originName = new javax.swing.JLabel();
        atk = new javax.swing.JLabel();
        vert = new javax.swing.JLabel();
        skill = new javax.swing.JLabel();
        spezatk = new javax.swing.JLabel();
        spezvert = new javax.swing.JLabel();
        init = new javax.swing.JLabel();
        bild = new javax.swing.JLabel();

        typ.setText("Typ: ");

        typ1.setForeground(new java.awt.Color(204, 0, 0));
        typ1.setText("Typ1 /");

        typ2.setForeground(new java.awt.Color(255, 0, 0));
        typ2.setText("Typ2");

        sum.setText("Wertesumme:         ");

        level.setText("level");

        originName.setText("Pokemon");

        atk.setText("Angriff:                     ");

        vert.setText("Verteidigung:           ");

        skill.setText("Fähigkeit: Adlerauge");

        spezatk.setText("Spezialangriff:          ");

        spezvert.setText("Spezialverteidigung: ");

        init.setText("Initiative:                  ");

        bild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pokemon/img/abstract.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bild)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(atk)
                            .addGap(67, 67, 67))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(vert)
                            .addGap(76, 76, 76))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(spezatk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(spezvert, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(init, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(typ)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(typ1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(typ2))
                                .addComponent(sum, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(70, 70, 70)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(originName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(skill)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(originName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(level)
                            .addComponent(skill))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typ)
                            .addComponent(typ1)
                            .addComponent(typ2))
                        .addGap(6, 6, 6)
                        .addComponent(atk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spezatk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spezvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(init)
                        .addGap(12, 12, 12)
                        .addComponent(sum))
                    .addComponent(bild))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atk;
    private javax.swing.JLabel bild;
    private javax.swing.JLabel init;
    private javax.swing.JLabel level;
    private javax.swing.JLabel originName;
    private javax.swing.JLabel skill;
    private javax.swing.JLabel spezatk;
    private javax.swing.JLabel spezvert;
    private javax.swing.JLabel sum;
    private javax.swing.JLabel typ;
    private javax.swing.JLabel typ1;
    private javax.swing.JLabel typ2;
    private javax.swing.JLabel vert;
    // End of variables declaration//GEN-END:variables
}
